spring:
  application:
    name: cloudthread-spring-cloud-config-starter-example
  datasource:
    url: jdbc:mysql://localhost:3316/cloudthread_dev
    username: root
    password: root
cloudthread:
  enable: true
  web-config:
    core-pool-size: 10
    maximum-pool-size: 50
    keep-alive-time-seconds: 60
  notify-config:
    subscribers: "ops@aston.com,dev@aston.com"
    intervals: 10
  config-file-type: yaml
  monitor-config:
    enable: true
    collect-type: micrometer
    collect-interval-seconds: 15
executors:
  - thread-pool-uid: cloudthread-producer
    core-pool-size: 5
    maximum-pool-size: 10
    queue-capacity: 500
    keep-alive-time-seconds: 30
    working-queue: LinkedBlockingQueue
    rejected-handler: AbortPolicy
    allow-core-thread-timeout: true
  - thread-pool-uid: cloudthread-consumer
    core-pool-size: 10
    maximum-pool-size: 20
    queue-capacity: 1000
    keep-alive-time-seconds: 60
    working-queue: LinkedBlockingQueue
    rejected-handler: AbortPolicy
    allow-core-thread-timeout: true