spring:
  application:
    name: spring-cloud-bus-app
datasource:
  url: jdbc:mysql://localhost:3306/spring-cloud-bus-app
  username: rurutia
  password: rurutia
custom:
  featureToggle:
    enableAwesomeFeature: true
