spring:
  config:
    import: "optional:consul:"
  application:
    name: spring-consul-config-app
  cloud:
    consul:
      # in dev mode, declare the environment variable in the IDEA/Edit Configuration
      host: ${SPRING_CLOUD_CONSUL_HOST:consul-consul-server.consul}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      config:
        watch:
          enabled: true
          delay: 10000 # MS
        format: yaml
        prefixes:
          - config/spring-consul-config-app
  profiles:
    active: prod

server:
  port: 8180

custom:
  config:
    featureA: true
    featureB: "Hello, Hands-on Lab!"
    maxItems: 1000000 
    message: "Welcome to Flux + Consul integration demo!"
